spring:
  application:
    name: manager-auth
server:
  port: 8087
  context-path: /auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

auth:
  userName: manager-auth
  userPwd: 123
  roles: ROLE_admin
  clientId: zuul_server
  secret: secret
  grantType: authorization_code
  key: springcloud123